on:
  push:
    branches:
      - master

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: go

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          set -ex
          echo "${{ toJSON(steps.release.outputs) }}"

          export RELEASE_VERSION=${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}-rc.$(node -e "console.log('$(git describe --tags)'.split('-')[1])")
          export RELEASE_CANDIDATE=true

      - if: ${{ steps.release.outputs.release_created }}
        run: |
          set -ex
          export RELEASE_VERISON=${{ steps.release.outputs.tag_name }}
          export RELEASE_CANDIDATE=false

      - uses: actions/setup-go@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          go-version: "^1.21.0" # The Go version to download (if necessary) and use.

      - name: Build release artifacts
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make deps
          make all
          ln -s auth gotrue
          tar -czvf auth-v$RELEASE_VERSION-x86.tar.gz auth gotrue migrations/
          mv auth-arm64 auth
          tar -czvf auth-v$RELEASE_VERSION-arm64.tar.gz auth gotrue migrations/

      - name: Upload release artifacts
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -ex

          if [ "$RELEASE_CANDIDATE" != "true" ]
          then
            gh release upload $RELEASE_VERSION ./auth-v$RELEASE_VERSION-x86.tar.gz ./auth-v-arm64.tar.gz
          fi

          #publish:
          #  needs:
          #    - releaseplease
          #  if: success() && needs.releaseplease.outputs.release_created
          #  # Call publish explicitly because events from actions cannot trigger more actions
          #  uses: ./.github/workflows/publish.yml
          #  with:
          #    version: v${{ needs.release.outputs.tag_name }}
          #  secrets: inherit
